name: iris
description: A complete abstraction of client <-> server communication
author: Matias Meno <m@tias.me>
version: 0.10.1
homepage: https://enyo.github.io/iris
dependencies:
  logging: ">=0.9.1+1 <0.12.0"
  annotation_crawler: ">=0.1.0 <0.2.0"
  protobuf: ">=0.3.3 <0.4.0"
  route: ">=0.4.6 <0.5.0"
  barback: ">=0.13.0 <0.16.0"
  path: ">=1.1.0 <2.0.0"
dev_dependencies:
  unittest: ">=0.11.0 <0.12.0"
  mock: ">=0.11.0 <0.12.0"
