name: remote_services
description: A complete abstraction of client <-> server communication
author: Matias Meno <m@tias.me>
version: 0.2.2
homepage: https://github.com/enyo/remote-services
dependencies:
  logging: ">=0.9.1+1 <0.10.0"
  annotation_crawler: ">=0.1.0 <0.2.0"
  protobuf: ">=0.3.3 <0.4.0"
  route: ">=0.4.6 <0.5.0"
  barback: ">=0.12.0 <0.13.0"
  path: ">=1.1.0 <2.0.0"
dev_dependencies:
  unittest: ">=0.10.1 <0.11.0"
